/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import javax.swing.JOptionPane;

/**
 *
 * @author Juan Carlos Vilarrubia
 */
public class ClockDemo extends javax.swing.JFrame {

    /**
     * Creates new form ClockDemo
     */
    public ClockDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digitalClockBean1 = new digitalclockbean.DigitalClockBean();
        digitalClockBean2 = new digitalclockbean.DigitalClockBean();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clock Demo");
        setAlwaysOnTop(true);
        setResizable(false);

        digitalClockBean1.setAlarm(new digitalclockbean.Alarm(20, 20, true, "Alarma lanzada desde reloj con formato 12H"));
        digitalClockBean1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "12H Clock", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Monaco", 0, 14))); // NOI18N
        digitalClockBean1.setFont(new java.awt.Font("Monaco", 0, 36)); // NOI18N
        digitalClockBean1.addAlarmListener(new digitalclockbean.AlarmListener() {
            public void launchAlarm(digitalclockbean.AlarmEvent evt) {
                digitalClockBean1LaunchAlarm(evt);
            }
        });

        digitalClockBean2.setAlarm(new digitalclockbean.Alarm(20, 20, true, "Alarma lamzada dede reloj con formato de 24H"));
        digitalClockBean2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "24H Clock", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Monaco", 0, 14))); // NOI18N
        digitalClockBean2.setFont(new java.awt.Font("Monaco", 0, 36)); // NOI18N
        digitalClockBean2.setFormat24(true);
        digitalClockBean2.addAlarmListener(new digitalclockbean.AlarmListener() {
            public void launchAlarm(digitalclockbean.AlarmEvent evt) {
                digitalClockBean2LaunchAlarm(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(digitalClockBean1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(digitalClockBean2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(digitalClockBean1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(digitalClockBean2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void digitalClockBean1LaunchAlarm(digitalclockbean.AlarmEvent evt) {//GEN-FIRST:event_digitalClockBean1LaunchAlarm

        JOptionPane.showMessageDialog(null, ((digitalclockbean.DigitalClockBean) evt.getSource()).getAlarm().getMessage(), "Alarma 12H", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_digitalClockBean1LaunchAlarm

    private void digitalClockBean2LaunchAlarm(digitalclockbean.AlarmEvent evt) {//GEN-FIRST:event_digitalClockBean2LaunchAlarm
        JOptionPane.showMessageDialog(null, ((digitalclockbean.DigitalClockBean) evt.getSource()).getAlarm().getMessage(), "Alarma 24H", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_digitalClockBean2LaunchAlarm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClockDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClockDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClockDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClockDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClockDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private digitalclockbean.DigitalClockBean digitalClockBean1;
    private digitalclockbean.DigitalClockBean digitalClockBean2;
    // End of variables declaration//GEN-END:variables
}
